### ISSUE TITLE
[Bug]: asyncmy.errors.OperationalError: (1045, "Access denied for user 'root'@'172.28.0.4' (using password: YES)")

### ISSUE THREAD

**Issue by lostsnow** [PaiGramTeam/HonkaiStarRailGram#41]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/PaiGramTeam/PaiGram/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 程序版本 （Commit Id）

23956ce426af921397285c862a7eaea45724e5fd

### 运行环境

Ubuntu

### 运行架构

AMD64

### 重现步骤

```
docker compose build
docker compose up -d
```

### 期望的结果是什么？

Run successfully

### 实际的结果是什么？

```
# docker compose logs -f 
pamgram-pam-1    | [INFO  wait] --------------------------------------------------------
pamgram-pam-1    | [INFO  wait]  docker-compose-wait 2.12.1
pamgram-pam-1    | [INFO  wait] ---------------------------
pamgram-pam-1    | [DEBUG wait] Starting with configuration:
pamgram-pam-1    | [DEBUG wait]  - Hosts to be waiting for: [mysql:3306, redis:6379]
pamgram-pam-1    | [DEBUG wait]  - Paths to be waiting for: []
pamgram-pam-1    | [DEBUG wait]  - Timeout before failure: 30 seconds 
pamgram-pam-1    | [DEBUG wait]  - TCP connection timeout before retry: 5 seconds 
pamgram-pam-1    | [DEBUG wait]  - Sleeping time before checking for hosts/paths availability: 0 seconds
pamgram-pam-1    | [DEBUG wait]  - Sleeping time once all hosts/paths are available: 0 seconds
pamgram-pam-1    | [DEBUG wait]  - Sleeping time between retries: 1 seconds
pamgram-pam-1    | [DEBUG wait] --------------------------------------------------------
pamgram-pam-1    | [INFO  wait] Checking availability of host [mysql:3306]
pamgram-pam-1    | [INFO  wait] Host [mysql:3306] is now available!
pamgram-pam-1    | [INFO  wait] --------------------------------------------------------
pamgram-pam-1    | [INFO  wait] Checking availability of host [ redis:6379]
pamgram-pam-1    | [INFO  wait] Host [ redis:6379] is now available!
pamgram-pam-1    | [INFO  wait] --------------------------------------------------------
pamgram-pam-1    | [INFO  wait] docker-compose-wait - Everything's fine, the application can now start!
pamgram-pam-1    | [INFO  wait] --------------------------------------------------------
WARN[0000] Can't retrieve logs for "pamgram-mysql-1": Error response from daemon: configured logging driver does not support reading 
WARN[0000] Can't retrieve logs for "pamgram-redis-1": Error response from daemon: configured logging driver does not support reading 
pamgram-pam-1    | Traceback (most recent call last):
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
pamgram-pam-1    |     self._dbapi_connection = engine.raw_connection()
pamgram-pam-1    |                              ^^^^^^^^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3292, in raw_connection
pamgram-pam-1    |     return self.pool.connect()
pamgram-pam-1    |            ^^^^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 452, in connect
pamgram-pam-1    |     return _ConnectionFairy._checkout(self)
pamgram-pam-1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1269, in _checkout
pamgram-pam-1    |     fairy = _ConnectionRecord.checkout(pool)
pamgram-pam-1    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
pamgram-pam-1    |     rec = pool._do_get()
pamgram-pam-1    |           ^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 284, in _do_get
pamgram-pam-1    |     return self._create_connection()
pamgram-pam-1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
pamgram-pam-1    |     return _ConnectionRecord(self)
pamgram-pam-1    |            ^^^^^^^^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
pamgram-pam-1    |     self.__connect()
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
pamgram-pam-1    |     with util.safe_reraise():
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
pamgram-pam-1    |     raise exc_value.with_traceback(exc_tb)
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
pamgram-pam-1    |     self.dbapi_connection = connection = pool._invoke_creator(self)
pamgram-pam-1    |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 637, in connect
pamgram-pam-1    |     return dialect.connect(*cargs, **cparams)
pamgram-pam-1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 616, in connect
pamgram-pam-1    |     return self.loaded_dbapi.connect(*cargs, **cparams)
pamgram-pam-1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/dialects/mysql/asyncmy.py", line 281, in connect
pamgram-pam-1    |     await_only(creator_fn(*arg, **kw)),
pamgram-pam-1    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 125, in await_only
pamgram-pam-1    |     return current.driver.switch(awaitable)  # type: ignore[no-any-return]
pamgram-pam-1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 185, in greenlet_spawn
pamgram-pam-1    |     value = await result
pamgram-pam-1    |             ^^^^^^^^^^^^
pamgram-pam-1    |   File "asyncmy/connection.pyx", line 1343, in _connect
pamgram-pam-1    |   File "asyncmy/connection.pyx", line 594, in connect
pamgram-pam-1    |   File "asyncmy/connection.pyx", line 572, in asyncmy.connection.Connection.connect
pamgram-pam-1    |   File "asyncmy/connection.pyx", line 849, in _request_authentication
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/asyncmy/auth.py", line 245, in caching_sha2_password_auth
pamgram-pam-1    |     pkt = await _roundtrip(conn, data)
pamgram-pam-1    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/asyncmy/auth.py", line 115, in _roundtrip
pamgram-pam-1    |     pkt = await conn.read_packet()
pamgram-pam-1    |           ^^^^^^^^^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "asyncmy/connection.pyx", line 644, in read_packet
pamgram-pam-1    |   File "asyncmy/protocol.pyx", line 190, in asyncmy.protocol.MysqlPacket.raise_for_error
pamgram-pam-1    |   File "asyncmy/protocol.pyx", line 194, in asyncmy.protocol.MysqlPacket.raise_for_error
pamgram-pam-1    |   File "asyncmy/errors.pyx", line 128, in asyncmy.errors.raise_mysql_exception
pamgram-pam-1    |   File "asyncmy/errors.pyx", line 137, in asyncmy.errors.raise_mysql_exception
pamgram-pam-1    | asyncmy.errors.OperationalError: (1045, "Access denied for user 'root'@'172.28.0.4' (using password: YES)")
pamgram-pam-1    | 
pamgram-pam-1    | The above exception was the direct cause of the following exception:
pamgram-pam-1    | 
pamgram-pam-1    | Traceback (most recent call last):
pamgram-pam-1    |   File "/app/venv/bin/alembic", line 8, in <module>
pamgram-pam-1    |     sys.exit(main())
pamgram-pam-1    |              ^^^^^^
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/alembic/config.py", line 630, in main
pamgram-pam-1    |     CommandLine(prog=prog).main(argv=argv)
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/alembic/config.py", line 624, in main
pamgram-pam-1    |     self.run_cmd(cfg, options)
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/alembic/config.py", line 601, in run_cmd
pamgram-pam-1    |     fn(
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/alembic/command.py", line 401, in upgrade
pamgram-pam-1    |     script.run_env()
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/alembic/script/base.py", line 585, in run_env
pamgram-pam-1    |     util.load_python_file(self.dir, "env.py")
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
pamgram-pam-1    |     module = load_module_py(module_id, path)
pamgram-pam-1    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 109, in load_module_py
pamgram-pam-1    |     spec.loader.exec_module(module)  # type: ignore
pamgram-pam-1    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "<frozen importlib._bootstrap_external>", line 994, in exec_module
pamgram-pam-1    |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
pamgram-pam-1    |   File "/app/alembic/env.py", line 134, in <module>
pamgram-pam-1    |     asyncio.run(run_migrations_online())
pamgram-pam-1    |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
pamgram-pam-1    |     return runner.run(main)
pamgram-pam-1    |            ^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
pamgram-pam-1    |     return self._loop.run_until_complete(task)
pamgram-pam-1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
pamgram-pam-1    |     return future.result()
pamgram-pam-1    |            ^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/app/alembic/env.py", line 125, in run_migrations_online
pamgram-pam-1    |     async with connectable.connect() as connection:
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/base.py", line 125, in __aenter__
pamgram-pam-1    |     return await self.start(is_ctxmanager=True)
pamgram-pam-1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/engine.py", line 270, in start
pamgram-pam-1    |     await greenlet_spawn(self.sync_engine.connect)
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 190, in greenlet_spawn
pamgram-pam-1    |     result = context.throw(*sys.exc_info())
pamgram-pam-1    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3268, in connect
pamgram-pam-1    |     return self._connection_cls(self)
pamgram-pam-1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
pamgram-pam-1    |     Connection._handle_dbapi_exception_noconnection(
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2430, in _handle_dbapi_exception_noconnection
pamgram-pam-1    |     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
pamgram-pam-1    |     self._dbapi_connection = engine.raw_connection()
pamgram-pam-1    |                              ^^^^^^^^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3292, in raw_connection
pamgram-pam-1    |     return self.pool.connect()
pamgram-pam-1    |            ^^^^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 452, in connect
pamgram-pam-1    |     return _ConnectionFairy._checkout(self)
pamgram-pam-1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1269, in _checkout
pamgram-pam-1    |     fairy = _ConnectionRecord.checkout(pool)
pamgram-pam-1    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
pamgram-pam-1    |     rec = pool._do_get()
pamgram-pam-1    |           ^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 284, in _do_get
pamgram-pam-1    |     return self._create_connection()
pamgram-pam-1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
pamgram-pam-1    |     return _ConnectionRecord(self)
pamgram-pam-1    |            ^^^^^^^^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
pamgram-pam-1    |     self.__connect()
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
pamgram-pam-1    |     with util.safe_reraise():
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
pamgram-pam-1    |     raise exc_value.with_traceback(exc_tb)
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
pamgram-pam-1    |     self.dbapi_connection = connection = pool._invoke_creator(self)
pamgram-pam-1    |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 637, in connect
pamgram-pam-1    |     return dialect.connect(*cargs, **cparams)
pamgram-pam-1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 616, in connect
pamgram-pam-1    |     return self.loaded_dbapi.connect(*cargs, **cparams)
pamgram-pam-1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/dialects/mysql/asyncmy.py", line 281, in connect
pamgram-pam-1    |     await_only(creator_fn(*arg, **kw)),
pamgram-pam-1    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 125, in await_only
pamgram-pam-1    |     return current.driver.switch(awaitable)  # type: ignore[no-any-return]
pamgram-pam-1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 185, in greenlet_spawn
pamgram-pam-1    |     value = await result
pamgram-pam-1    |             ^^^^^^^^^^^^
pamgram-pam-1    |   File "asyncmy/connection.pyx", line 1343, in _connect
pamgram-pam-1    |   File "asyncmy/connection.pyx", line 594, in connect
pamgram-pam-1    |   File "asyncmy/connection.pyx", line 572, in asyncmy.connection.Connection.connect
pamgram-pam-1    |   File "asyncmy/connection.pyx", line 849, in _request_authentication
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/asyncmy/auth.py", line 245, in caching_sha2_password_auth
pamgram-pam-1    |     pkt = await _roundtrip(conn, data)
pamgram-pam-1    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "/app/venv/lib/python3.12/site-packages/asyncmy/auth.py", line 115, in _roundtrip
pamgram-pam-1    |     pkt = await conn.read_packet()
pamgram-pam-1    |           ^^^^^^^^^^^^^^^^^^^^^^^^
pamgram-pam-1    |   File "asyncmy/connection.pyx", line 644, in read_packet
pamgram-pam-1    |   File "asyncmy/protocol.pyx", line 190, in asyncmy.protocol.MysqlPacket.raise_for_error
pamgram-pam-1    |   File "asyncmy/protocol.pyx", line 194, in asyncmy.protocol.MysqlPacket.raise_for_error
pamgram-pam-1    |   File "asyncmy/errors.pyx", line 128, in asyncmy.errors.raise_mysql_exception
pamgram-pam-1    |   File "asyncmy/errors.pyx", line 137, in asyncmy.errors.raise_mysql_exception
pamgram-pam-1    | sqlalchemy.exc.OperationalError: (asyncmy.errors.OperationalError) (1045, "Access denied for user 'root'@'172.28.0.4' (using password: YES)")
pamgram-pam-1    | (Background on this error at: https://sqlalche.me/e/20/e3q8)
pamgram-pam-1 exited with code 0
```

### 简单的复现代码/链接（可选）

```python3
.env


# debug 开关
DEBUG=false

AUTO_RELOAD=false
RELOAD_DELAY=0.25
RELOAD_DIRS=[]
RELOAD_INCLUDE=[]
RELOAD_EXCLUDE=[]

# Database
DB_DRIVER_NAME=mysql+asyncmy
DB_HOST=mysql
DB_PORT=3306
DB_USERNAME=root
DB_PASSWORD=xxx
DB_DATABASE=pam

# Redis
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_DB=0
REDIS_PASSWORD=""

# 联系 https://t.me/BotFather 使用 /newbot 命令创建机器人并获取 token
BOT_TOKEN="xxx"

# bot 所有者
OWNER=11111111

# 记录错误并发送消息通知开发人员 可选配置项
ERROR_NOTIFICATION_CHAT_ID=1111111

# 文章推送群组 可选配置项
# CHANNELS=[]

# 是否允许机器人邀请到其他群 默认不允许 如果允许 可以允许全部人或有认证选项 可选配置项
# JOIN_GROUPS = "NO_ALLOW"

# 群验证功能 可选配置项
# VERIFY_GROUPS=[]

# logger 配置 可选配置项
# LOGGER_NAME="HonkaiStarRailGram"
# 打印时的宽度
LOGGER_WIDTH=150
# log 文件存放目录
# LOGGER_LOG_PATH="logs"
# log 时间格式，参考 datetime.strftime
# LOGGER_TIME_FORMAT="[%Y-%m-%d %X]"
# log 高亮关键词
# LOGGER_RENDER_KEYWORDS=["BOT"]
# traceback 相关配置
# LOGGER_TRACEBACK_MAX_FRAMES=20
# LOGGER_LOCALS_MAX_DEPTH=0
# LOGGER_LOCALS_MAX_LENGTH=10
# LOGGER_LOCALS_MAX_STRING=80
# 可被 logger 打印的 record 的名称（默认包含了 LOGGER_NAME ）
LOGGER_FILTERED_NAMES=["uvicorn","ErrorPush","ApiHelper"]

# Request 超时配置 可选配置项
# READ_TIMEOUT=7
# 指定等待服务器响应的最长时间
# WRITE_TIMEOUT=10
# 指定等待写入操作完成的最长时间（就网络套接字而言，即请求或上传一个文件）
# CONNECT_TIMEOUT=10
# 指定等待连接到服务器的最长时间
# POOL_TIMEOUT=10
# Bot.Update 超时配置
# TIMEOUT=10
# 服务器出现故障时Updater的引导阶段重试时间
# UPDATE_READ_TIMEOUT=42
# UPDATE_WRITE_TIMEOUT=10
# UPDATE_CONNECT_TIMEOUT=10
# UPDATE_POOL_TIMEOUT=10

# genshin.py 缓存配置 可选配置项
# GENSHIN_TTL = 3600

# mtp 客户端 可选配置项
# API_ID=12345
# API_HASH="abcdefg"

# ENKA_NETWORK_API 可选配置项（暂时无法使用）
# ENKA_NETWORK_API_AGENT=""

# Web Server
# WEB_ENABLE=False # 是否开启 WebServer
# WEB_HOST=localhost
# WEB_PORT=8080

# error
# ERROR_PB_URL=https://fars.ee
# ERROR_PB_SUNSET=43200
# ERROR_PB_MAX_LINES=1000
# ERROR_SENTRY_DSN=

# Notice
NOTICE_USER_MISMATCH="再乱点我叫西风骑士团、千岩军、天领奉行、三十人团和风纪官了！"

# Plugin
# PLUGIN_DOWNLOAD_FILE_MAX_SIZE=5
```
```


### 日志记录（可选）

_No response_

### 补充说明（可选）

_No response_

**Comment by lostsnow** [comment]
docker-compose.yml
```
version: "3.1"

services:
  redis:
    image: docker.io/redis:7-alpine
    restart: always
    volumes:
      - ./redis_data:/data
    logging:
      driver: none

  mysql:
    image: docker.io/ubuntu/mysql:8.0-22.04_beta
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "127.0.0.1:3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=xxx
      - MYSQL_USER=root
      - MYSQL_DATABASE=pam
    logging:
      driver: none

  pam:
    build: .
    image: docker.io/paigramteam/pamgram:v1
    restart: always
    environment:
      - WAIT_HOSTS=mysql:3306, redis:6379
    depends_on:
      - redis
      - mysql
    volumes:
      - ./.env:/app/.env
      - ./cache:/app/cache
      - ./data:/app/data
      - ./logs:/app/logs
      - ./report:/app/report
```


![图片](https://github.com/PaiGramTeam/PamGram/assets/220461/a2983e1e-d089-4ed1-81c8-2c27a6f037aa)

![图片](https://github.com/PaiGramTeam/PamGram/assets/220461/3cf4740d-88e2-4020-803a-01f0cd374964)

**Comment by luoshuijs** [comment]
目前我们在前一周收到了这个问题，从 `alembic` 连接数据库的时候就会出现这个问题，而 Bot 连接数据并不会出现问题，后面因为 SQLite 能够运行加上最近开发人员挺忙的一直没理。

**Comment by luoshuijs** [comment]
估计找到问题了，在 `alembic/env.py` 中，在给 `alembic_config` 设置 `sqlalchemy.url` 时，直接转换的会默认隐藏密码，你尝试把下述代码进行修改。

原来：
```python3
alembic_cfg.set_main_option("sqlalchemy.url", str(new_url))
```
修改后：
```python3
alembic_cfg.set_main_option("sqlalchemy.url", new_url.render_as_string(hide_password=False))
```

不久后我会推送新的修复 commit

**Comment by luoshuijs** [comment]
之前还好好的，估计是上游的更变导致的问题

**Comment by lostsnow** [comment]
> 估计找到问题了，在 `alembic/env.py` 中，在给 `alembic_config` 设置 `sqlalchemy.url` 时，直接转换的会默认隐藏密码，你尝试把下述代码进行修改。
> 
> 原来：
> 
> ```python
> alembic_cfg.set_main_option("sqlalchemy.url", str(new_url))
> ```
> 
> 修改后：
> 
> ```python
> alembic_cfg.set_main_option("sqlalchemy.url", new_url.render_as_string(hide_password=False))
> ```
> 
> 不久后我会推送新的修复 commit

solved, thanks!

```
pamgram-pam-1    | [INFO  wait] --------------------------------------------------------
pamgram-pam-1    | [INFO  wait] docker-compose-wait - Everything's fine, the application can now start!
pamgram-pam-1    | [INFO  wait] --------------------------------------------------------
pamgram-pam-1    | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
pamgram-pam-1    | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
pamgram-pam-1    | [2023-12-27 14:36:33] INFO     正在启动 BOT 中...                                                                          gram_core.application 138  

...

pamgram-pam-1    |                       SUCCESS  BOT 初始化成功                                                                              gram_core.application 186  
pamgram-pam-1    |                       SUCCESS  BOT 启动成功                                                                                gram_core.application 192  
```

**Comment by luoshuijs** [comment]
已经在 https://github.com/PaiGramTeam/PaiGram/pull/739 修复
